In [ ]:
import pandas as pd 
print(pd.__version__)

2.3.3

In [ ]:
df=pd.read_csv(r"C:\Users\anjal\Downloads\phiusiil+phishing+url+dataset\PhiUSIIL_Phishing_URL_Dataset.csv")

In [6]:
df.head()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

In [7]:
df.shape

(235795, 56)

In [8]:
df.columns

Index(['FILENAME', 'URL', 'URLLength', 'Domain', 'DomainLength', 'IsDomainIP',
       'TLD', 'URLSimilarityIndex', 'CharContinuationRate',
       'TLDLegitimateProb', 'URLCharProb', 'TLDLength', 'NoOfSubDomain',
       'HasObfuscation', 'NoOfObfuscatedChar', 'ObfuscationRatio',
       'NoOfLettersInURL', 'LetterRatioInURL', 'NoOfDegitsInURL',
       'DegitRatioInURL', 'NoOfEqualsInURL', 'NoOfQMarkInURL',
       'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL',
       'SpacialCharRatioInURL', 'IsHTTPS', 'LineOfCode', 'LargestLineLength',
       'HasTitle', 'Title', 'DomainTitleMatchScore', 'URLTitleMatchScore',
       'HasFavicon', 'Robots', 'IsResponsive', 'NoOfURLRedirect',
       'NoOfSelfRedirect', 'HasDescription', 'NoOfPopup', 'NoOfiFrame',
       'HasExternalFormSubmit', 'HasSocialNet', 'HasSubmitButton',
       'HasHiddenFields', 'HasPasswordField', 'Bank', 'Pay', 'Crypto',
       'HasCopyrightInfo', 'NoOfImage', 'NoOfCSS', 'NoOfJS', 'NoOfSelfRef',
       'NoOfEmptyRef', 'NoOfExternalRef', 'label'],
      dtype='object')

In [9]:
df.isnull().sum()

FILENAME                      0
URL                           0
URLLength                     0
Domain                        0
DomainLength                  0
IsDomainIP                    0
TLD                           0
URLSimilarityIndex            0
CharContinuationRate          0
TLDLegitimateProb             0
URLCharProb                   0
TLDLength                     0
NoOfSubDomain                 0
HasObfuscation                0
NoOfObfuscatedChar            0
ObfuscationRatio              0
NoOfLettersInURL              0
LetterRatioInURL              0
NoOfDegitsInURL               0
DegitRatioInURL               0
NoOfEqualsInURL               0
NoOfQMarkInURL                0
NoOfAmpersandInURL            0
NoOfOtherSpecialCharsInURL    0
SpacialCharRatioInURL         0
IsHTTPS                       0
LineOfCode                    0
LargestLineLength             0
HasTitle                      0
Title                         0
DomainTitleMatchScore         0
URLTitleMatchScore            0
HasFavicon                    0
Robots                        0
IsResponsive                  0
NoOfURLRedirect               0
NoOfSelfRedirect              0
HasDescription                0
NoOfPopup                     0
NoOfiFrame                    0
HasExternalFormSubmit         0
HasSocialNet                  0
HasSubmitButton               0
HasHiddenFields               0
HasPasswordField              0
Bank                          0
Pay                           0
Crypto                        0
HasCopyrightInfo              0
NoOfImage                     0
NoOfCSS                       0
NoOfJS                        0
NoOfSelfRef                   0
NoOfEmptyRef                  0
NoOfExternalRef               0
label                         0
dtype: int64

In [10]:
df.duplicated().sum()

0

In [11]:
df=df.drop_duplicates()

In [12]:
df["label"].unique()

array([1, 0], dtype=int64)

In [ ]:
df.columns

Index(['FILENAME', 'URL', 'URLLength', 'Domain', 'DomainLength', 'IsDomainIP',
       'TLD', 'URLSimilarityIndex', 'CharContinuationRate',
       'TLDLegitimateProb', 'URLCharProb', 'TLDLength', 'NoOfSubDomain',
       'HasObfuscation', 'NoOfObfuscatedChar', 'ObfuscationRatio',
       'NoOfLettersInURL', 'LetterRatioInURL', 'NoOfDegitsInURL',
       'DegitRatioInURL', 'NoOfEqualsInURL', 'NoOfQMarkInURL',
       'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL',
       'SpacialCharRatioInURL', 'IsHTTPS', 'LineOfCode', 'LargestLineLength',
       'HasTitle', 'Title', 'DomainTitleMatchScore', 'URLTitleMatchScore',
       'HasFavicon', 'Robots', 'IsResponsive', 'NoOfURLRedirect',
       'NoOfSelfRedirect', 'HasDescription', 'NoOfPopup', 'NoOfiFrame',
       'HasExternalFormSubmit', 'HasSocialNet', 'HasSubmitButton',
       'HasHiddenFields', 'HasPasswordField', 'Bank', 'Pay', 'Crypto',
       'HasCopyrightInfo', 'NoOfImage', 'NoOfCSS', 'NoOfJS', 'NoOfSelfRef',
       'NoOfEmptyRef', 'NoOfExternalRef', 'label'],
      dtype='object')

In [14]:
x=df.drop("label",axis=1)
y= df["label"]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_temp,y_train,y_temp=train_test_split(x,y,test_size=0.30, random_state=42,stratify=y)
x_val ,x_test ,y_val ,y_test =train_test_split(x_temp,y_temp, test_size=0.50,random_state=42,stratify=y_temp)

In [16]:
print("Training set:",x_train.shape)
print("Validation set:",x_val.shape)
print("test set:",x_test.shape)

Training set: (165056, 55)
Validation set: (35369, 55)
test set: (35370, 55)

In [17]:
train_df = pd.concat([x_train,y_train],axis=1)
val_df = pd.concat([x_val,y_val],axis=1)
test_df = pd.concat([x_test,y_test],axis=1)

In [22]:
train_df.to_csv("train.csv", index = False)
val_df.to_csv("val.csv", index = False)
test_df.to_csv("test.csv", index = False)
print("saved train.csv,val.csv,test.csv")

saved train.csv,val.csv,test.csv

In [18]:
output_file_path ='cleaned_phishing.csv'
df.to_csv(output_file_path,index=False)
print(f"{output_file_path}")

cleaned_phishing.csv

In [ ]:
import pandas as pd
import re
from urllib.parse import urlparse

def extract_features(url):

    parsed = urlparse(url)
    domain = parsed.netloc

    features = {}

    features['URLLength'] = len(url)
    features['DomainLength'] = len(domain)

    features['IsDomainIP'] = 1 if re.match(r'\d+\.\d+\.\d+\.\d+', domain) else 0

    features['TLDLength'] = len(domain.split('.')[-1]) if '.' in domain else 0

    features['NoOfSubDomain'] = max(domain.count('.') - 1, 0)

    features['HasObfuscation'] = 1 if '%' in url else 0

    features['NoOfObfuscatedChar'] = url.count('%')

    features['NoOfLettersInURL'] = sum(c.isalpha() for c in url)

    features['NoOfDegitsInURL'] = sum(c.isdigit() for c in url)

    features['NoOfEqualsInURL'] = url.count('=')

    features['NoOfQMarkInURL'] = url.count('?')

    features['NoOfAmpersandInURL'] = url.count('&')

    features['NoOfOtherSpecialCharsInURL'] = len(re.findall(r'[^\w]', url))

    features['IsHTTPS'] = 1 if parsed.scheme == "https" else 0

    features['Bank'] = 1 if "bank" in url.lower() else 0

    features['Pay'] = 1 if "pay" in url.lower() else 0

    features['Crypto'] = 1 if "crypto" in url.lower() else 0

    return features


df_features = df['url'].apply(extract_features).apply(pd.Series)

df_final = pd.concat([df_features, df['label']], axis=1)

df_final.to_csv("../notebooks/cleaned_phishing.csv", index=False)

print("Preprocessing completed")

:

In [21]:
import re 
def extract_url_features(url):
    return pd.Series({
        'url_length': len(url),
        'dot_count':url.count('.'),
        'hyphen_count':url.count('-'),
        'slash_count':url.count('/'),
        'digit_count': sum(char.isdigit() for char in url),
        'has_at_symbol': 1 if '@' in url else 0,
        'has_ip': 1 if re.match(r'\d+\.\d+\.\d+\.\d+', url) else 0
    })
url_features = df['URL'].apply(extract_url_features)
display(url_features.head())

,url_length,dot_count,hyphen_count,slash_count,digit_count,has_at_symbol,has_ip
0,32,2,0,2,0,0,0
1,24,2,1,2,0,0,0
2,30,3,0,2,0,0,0
3,27,2,0,2,0,0,0
4,34,2,0,2,0,0,0

In [ ]:
df = pd.read_csv("../notebooks/cleaned_phishing.csv")

print("total samples:", df.shape)
df.head()

total samples: (235795, 56)

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1